fields = {
    "dest_callsign": "KD8SPS",
    "src_callsign": "CQ    ",
    "src_ssid": 0,
    "dest_ssid": 0,
    "ctl": 3,
    "pid": 240,
    "primary_id": 0,
    "secondary_id": 66,
    "flags": 3,
    "packet_length": 62720,
    "header_checksum": 46197,
    "spacecraft": "GRIFEX",
    "rtc_unix_time": 1565404787,
    "numresets": 826,
    "avgnumactivetasks1": 11,
    "avgnumactivetasks5": 10,
    "avgnumactivetasks15": 9,
    "curnumrunnabletasks": 1,
    "totnumprocesses": 34,
    "lastprocesspid": 6212,
    "totmem": 31726,
    "freemem": 26989,
    "adcs_enable_status": 1,
    "sd_usage": 0,
    "datamnt_usage": 395665,
    "lithium_op_count": 11692,
    "lithium_msp430_temp": 27,
    "lithium_rssi": 84,
    "lithium_rx": 0,
    "lithium_tx": 1525545,
    "fcpu_temp_0": 1613,
    "fcpu_temp_1": 1583,
    "li_3v3_voltage": 3319,
    "fcpu_3v3_current": 97,
    "li_3v3_current": 39,
    "fcpu_3v3_voltage": 3313,
    "li_vbatt_voltage": 3791,
    "li_vbatt_current": 13,
    "battery_voltage": 3772,
    "battery_current": 1531,
    "battery_temperature": 1651,
    "battery_bus_voltage": 3786,
    "battery_bus_current": 15,
    "bus_voltage_5v": 3424,
    "bus_current_5v": 32,
    "input_current_5v": 21,
    "bus_voltage_3_3v": 3321,
    "bus_current_3_3v": 156,
    "input_current_3_3v": 87,
    "output_regulator_temperature": 1588,
    "eps_5v_voltage": 3426,
    "eps_5v_current": 136,
    "eps_3_3_voltage": 3318,
    "eps_3_3v_current": 178,
    "channel_1_panel_voltage_b": 356,
    "channel_1_panel_current_b": 20,
    "channel_1_output_voltage": 557,
    "channel_1_output_current": 13,
    "channel_1_module_temperature": 1581,
    "channel_1_board_temperature": 1580,
    "channel_2_panel_voltage_b": 2637,
    "channel_2_panel_current_b": 112,
    "channel_2_output_voltage": 3857,
    "channel_2_output_current": 36,
    "channel_2_module_temperature": 1570,
    "channel_2_board_temperature": 1574,
    "channel_3_panel_voltage_b": 261,
    "channel_3_panel_current_b": 5,
    "channel_3_output_voltage": 363,
    "channel_3_output_current": 1,
    "channel_3_module_temperature": 1573,
    "channel_3_board_temperature": 1570,
    "channel_4_panel_voltage_b": 2373,
    "channel_4_panel_current_b": 558,
    "channel_4_output_voltage": 3918,
    "channel_4_output_current": 165,
    "channel_4_module_temperature": 1555,
    "channel_4_board_temperature": 1561,
    "eps_ioe_state": 225,
    "eps_ioe_mode": 252,
    "tcb_temp_0": 1665,
    "tcb_temp_1": 1669,
    "tcb_temp_2": 1673,
    "adcs1_ioe_state": 0,
    "adcs1_ioe_mode": 192,
    "posy_mag_x": 42,
    "posy_mag_y": 23,
    "posy_mag_z": -109,
    "posx_mag_x": 97,
    "posx_mag_y": -63,
    "posx_mag_z": -37,
    "negy_mag_x": 154,
    "negy_mag_y": -15,
    "negy_mag_z": 56,
    "negx_mag_x": 210,
    "negx_mag_y": -7,
    "negx_mag_z": 241,
    "posy_internal_temperature": 2289,
    "posy_external_temperature": 2272,
    "posx_internal_temperature": 2558,
    "posx_external_temperature": 2516,
    "negy_internal_temperature": 2973,
    "negy_external_temperature": 2958,
    "negx_internal_temperature": 2743,
    "negx_external_temperature": 2730,
    "posy_photodiode": 897,
    "posx_photodiode": 2203,
    "negy_photodiode": 8,
    "negx_photodiode": 2,
    "mzint_ioe1_state": 136,
    "mzint_ioe1_mode": 51,
    "mzint_ioe2_state": 136,
    "mzint_ioe2_mode": 51,
    "marina_gpio_status_data": 76,
    "marina_completed_runs": 32,
    "marina_aborted_runs": 16,
    "marina_vbatt_voltage": 0,
    "marina_vbatt_current": 0,
    "marina_temperature": 900,
    "marina_2_5v_voltage": 2,
    "marina_1_0v_voltage": 2,
    "marina_exit_status": 0,
    "variable_1": 0,
    "variable_2": 255,
    "variable_3": 114,
    "variable_4": 61,
    "variable_5": 0,
    "variable_6": 190,
    "variable_7": 255,
    "variable_8": 255,
    "variable_9": 255,
    "variable_10": 255
}

# Define the template for the output line
line_template = 'Field(\'{}\', lambda x: x, None, \'{}\'),\n'

# Open the output file in write mode
with open('output.py', 'w') as output_file:
    # Write the initial part of the output
    output_file.write('self.normalizers = [\n')

    # Iterate over each field in the dictionary
    for field_name, field_value in fields.items():
        # Generate the Python code line for the current field
        line = line_template.format(field_name,
                                    field_name.replace('_', ' ').title())
        # Write the line to the output file
        output_file.write('    ' + line)

    # Write the closing part of the output
    output_file.write('] # pylint: disable=R0801\n')
