stages:
  - static
  - build
  - test
static:
  stage: static
  image: python:latest
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "flake8,isort,yapf,pylint"
build:
  stage: build
  image: python:latest
  before_script:
    - pip install tox~=3.8.0
  script:
    - rm -rf dist
    - tox -e "build"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - dist
test:
  stage: test
  image: python:latest
  before_script:
    - pip install tox~=3.8.0
  script:
    - tox -e "pytest"
